### PR TITLE
feat: new flag to apply factory to scope

### LINKED ISSUE #4: factory isn't called for context values?
seems like it might be a nice feature and a lot more consistent if the factory method were called on values pulled from the context on eval. my use case is a decimal.js adapter for math-codegen, all the methods assume decimal.js objects coming in since that's what the factory returns but then I have to create decimal objects when I supply the context object as well. would be nice to just call the factory for those as well. 

the adapter (WIP) is here if you're curious: https://github.com/creditiq/decimal-math-ops/blob/master/src/index.ts

thanks for this lib! great stuff!

### PR DESCRIPTION
**Pull request by mauriciopoppe**
Added the flag `applyFactoryToScope` to call the factory method on the scope values, fixes #4

### CODE REVIEW

**Comment by scamden** [comment]
This looks perfect!! Thanks for the quick reply! Do you have to check that value is a function because it could be one if the operation functions? Or are context values called first if they are functions?

**Review by scamden — COMMENTED** [review]
Also could I ask what the rawCallExpressionElements flag does while we’re talking here? :)
@mauriciopoppe ^

**Comment by mauriciopoppe** [comment]
my bad I didn't add a clear explanation on the readme of both raw* flags, luckily I wrote this test

https://github.com/mauriciopoppe/math-codegen/blob/3989c721bc14953035c186a9bb41631eade2bdef/test/index.js#L228-L240

So it means that the compile phase won't apply any transformations to any of the arguments when the function is called

**Comment by scamden** [comment]
oh ok awesome! thanks for the info! great lib!

**Pull request merged**
